site_name: Einführung in die Versionsverwaltung mit Git

nav:
  - Übersicht: index.md
  - 1 Einführung: content/1.md
  - 2 Kursübersicht: content/2.md
  - 3.1 Historische Entwicklung: content/3.md
  - 3.2 Grundlegende Konzepte: content/4.md
  - 3.3 Installation und erste Schritte: content/5.md
  - 4.1 Remote-Repositories: content/6.md
  - 4.2 GitHub/GitLab Integration: content/7.md
  - 4.3 Projektdateien und .gitignore: content/8.md
  - 5.1 Fortgeschrittene Features: content/9.md
  - 5.2 Projektadministration: content/10.md


theme:
  name: material
  palette:
    # primary: blue
    # accent: green
    primary: green
    accent: light green
  logo: assets/bfz_logo.svg
  favicon: assets/bfz_favicon.png
  features:
    - navigation.tracking
    - navigation.path
    - navigation.top
    - navigation.footer
    - toc.follow
    - toc.integrate
    - content.code.copy
    - content.code.annotate

markdown_extensions:
  - pymdownx.keys
  - admonition
  - pymdownx.details
  - pymdownx.superfences:
      custom_fences:
        - name: mermaid
          class: mermaid
          format: !!python/name:pymdownx.superfences.fence_code_format
  - toc:
      permalink: true
  - pymdownx.emoji:
      emoji_index: !!python/name:material.extensions.emoji.twemoji
      emoji_generator: !!python/name:material.extensions.emoji.to_svg
  - admonition
  - attr_list
  - md_in_html
  - pymdownx.arithmatex:
      generic: true
  - pymdownx.highlight:
      linenums: true

extra_css:
  - stylesheets/logo.css
  - stylesheets/grid.css
  - stylesheets/video_admonition.css
  - stylesheets/python_tutor_admonition.css
  - stylesheets/mermaid.css

extra_javascript:
  - javascripts/mathjax.js
  - https://unpkg.com/mathjax@3/es5/tex-mml-chtml.js
  
plugins:
    - search
    - macros

extra:
  social:
    - icon: fontawesome/brands/linkedin
      link: https://de.linkedin.com/company/bfz-ggmbh
    - icon: fontawesome/solid/globe
      link: https://www.bfz.de
    - icon: fontawesome/solid/graduation-cap
      link: https://www.bfz.de/ueber-uns

watch:
  - tasks

copyright: Copyright &copy; 2026 BFZ gGmbH